### ISSUE TITLE
Can't read property length of undefined when opening project from Atom's UI

### ISSUE THREAD

**Issue by bogas04** [o-d-i-n/all-contributors-atom#1]
### STR:
- Open Atom
- Go To File > Add Project Folder
- Open README.md file in this folder
- Attempt to use the package.
### Result:

```
Uncaught TypeError: Cannot read property 'length' of undefined
/Users/divjotsingh/.atom/packages/allcontributors/lib/allcontributors.coffee:73
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.Allcontributors.transform (/Users/divjotsingh/.atom/packages/allcontributors/lib/allcontributors.coffee:73:106)
    at atom-workspace.subscriptions.add.atom.commands.add.allcontributors:transform (/Users/divjotsingh/.atom/packages/allcontributors/lib/allcontributors.coffee:11:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.2.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.2.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.2.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.2.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/1.2.3/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.2.3/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Expected: Things to work normally

It works fine when I use cli to open project folder though.

**Comment by mbad0la** [comment]
@bogas04 should we close this issue?

**Comment by revelt** [comment]
I don't get this message, I've got project created for each of my libs... 

Can anybody confirm it's happening?

**Comment by mbad0la** [comment]
@bogas04 do you recall what the problem was? Was it something to do with "non-git" projects?
